### ISSUE TITLE
Niskaa Course List

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/niskaa#1]
@sinkinsona 
Hi Andrew.  Here is the latest excel spreadsheet for the ISO course for July to December
https://drive.google.com/file/d/0B95j4zfm5LiLTkZGQUxjcURfUVk/view?usp=sharing

**Comment by sinkinsona** [comment]
I have uploaded the latest courses + kept those already listed for May & June 2016.  For future updates please include in the excel template all courses that should be listed on the site.  Thanks
