### ISSUE TITLE
ISO Courses 2017

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/niskaa#5]
@sinkinsona 
Hi Andrew,
Here is the Excel spreadsheet highlighting the title changes to existing categories and the addition of a category. There are also changes to existing courses being moved and some new ones also.
https://drive.google.com/open?id=0B95j4zfm5LiLMWQ0cXNxanhyNU0

**Comment by SpecialKelsey** [comment]
@sinkinsona 
I added the final excel spreasheet for Jan to June 2017 including Dec 2016 in the Niskaa folder in GitHub.  I have shortened the list for 2017
https://drive.google.com/open?id=0B95j4zfm5LiLNjgxY2pFS1dtRVU

**Comment by SpecialKelsey** [comment]
@sinkinsona
Closed it by error.  Clicked on Comment and Close instead of just Comment.  Sorry about the confusion

**Comment by sinkinsona** [comment]
Will upload to the site in the next couple of days

**Comment by sinkinsona** [comment]
New courses for 2017 have been uploaded
