### ISSUE TITLE
ISO Courses 2017-PDF document

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/niskaa#6]
@sinkinsona 
Here are new, revised or courses we missed on the last upate.  
https://drive.google.com/drive/folders/0B95j4zfm5LiLNjgxY2pFS1dtRVU?usp=sharing

**Comment by sinkinsona** [comment]
I have uploaded all the pdf's and here is how you link to them
http://niskaa.com/iso-27032-lead-cybersecurity-manager_4p-fr.pdf

**Comment by SpecialKelsey** [comment]
Hi Andrew,
Sorry, but I forgot to add a few PDF
https://drive.google.com/drive/folders/0B95j4zfm5LiLNjgxY2pFS1dtRVU?usp=sharing
They are English and French of 
27002-Lead Manager
27035 Lead Incident Manager
30301 Lead Auditor and Implementer
37001 Lead Auditor and Implementer

**Comment by sinkinsona** [comment]
I have uploaded all the pdf that were missing

**Comment by SpecialKelsey** [comment]
@sinkinsona 
You're really going to hate me for this.  I missed one.  The more I review the Excel Spreadsheet the more I notice.  Sorry about that

ISO 27035 Manager

Also the link for the 37001 LA and LI did not work and I noticed the pdf were not on Google docs.


https://drive.google.com/open?id=0B95j4zfm5LiLNjgxY2pFS1dtRVU

**Comment by sinkinsona** [comment]
I will upload the latest PDF soon so if you have included them on the Google drive they will be uploaded.  For the linking issue you just need make the link as follows:
http://niskaa.com/The_name_of_the_course.pdf
Note:  If the name of the PDF document has white spaces these need to be replaced with %20.  Here is an example http://niskaa.com/name%20course.pdf

**Comment by sinkinsona** [comment]
All pdf's from https://drive.google.com/open?id=0B95j4zfm5LiLNjgxY2pFS1dtRVU have been uploaded
