### ISSUE TITLE
ISO Course Description

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/niskaa#8]
@sinkinsona 

Hi Andrew,
You got my email with the shareable link to the new ISO folder in google docs.  I just received these from PECB. They added the Niskaa Logo.
https://drive.google.com/drive/folders/0B95j4zfm5LiLLXl0VjZjc0ZrQ2c?usp=sharing

**Comment by sinkinsona** [comment]
The new pdf's have been uploaded
